version: '3.8'
services:
  postgres:
    container_name: postgres-14-book-lovers
    image: postgres:14.1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=adminBookLovers
      - POSTGRES_USER=postgres
      - POSTGRES_DB=booklovers
    hostname: postgres